apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vz17sb2jf-go 
  janus-idp.io/tekton: vz17sb2jf-go
  backstage.io/kubernetes-id: vz17sb2jf-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vz17sb2jf-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml