apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vz17sb2jf-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vz17sb2jf-go 
  name: vz17sb2jf-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vz17sb2jf-go 
